sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 #deactivate prompts in gcloud
before_install:
  # to encrypt service-account
  # docker run -it -v $(pwd):/app ruby:2.3 sh
  # gem install travis
  # travis login --pro
  # travis encrypt-file service-account.json -r marecica2/multi-docker --com
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-265412
  - gcloud config set compute/zone europe-west3-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t marecica2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run marecica2/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
